# Generated by Django 2.2.6 on 2019-10-03 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='language',
            field=models.CharField(choices=[('java', 'Java'), ('javascript', 'Javascript'), ('python', 'Python'), ('ruby', 'Ruby'), ('php', 'PHP'), ('go', 'Go')], default='java', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='solution_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessment.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='assessment',
            unique_together={('author', 'name')},
        ),
    ]
