# Generated by Django 2.2.6 on 2019-10-04 04:26

from django.db import migrations, models
import general.models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20191003_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='language',
            field=models.CharField(choices=[(general.models.Language('java'), 'Java'), (general.models.Language('javascript'), 'Javascript'), (general.models.Language('python'), 'Python'), (general.models.Language('ruby'), 'Ruby'), (general.models.Language('php'), 'PHP'), (general.models.Language('go'), 'Go')], max_length=255),
        ),
    ]
