# Generated by Django 2.2.6 on 2019-10-06 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_auto_20191004_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.Question')),
            ],
            options={
                'db_table': 'answers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AnswerSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('passed', models.BooleanField()),
                ('code', models.TextField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Answer')),
            ],
            options={
                'db_table': 'answer_submissions',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='questionresultsubmission',
            name='question_result',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='language',
            field=models.CharField(choices=[('java', 'Java'), ('javascript', 'Javascript'), ('python', 'Python'), ('ruby', 'Ruby'), ('go', 'Go')], max_length=255),
        ),
        migrations.DeleteModel(
            name='QuestionResult',
        ),
        migrations.DeleteModel(
            name='QuestionResultSubmission',
        ),
    ]
