# Generated by Django 2.2.6 on 2019-10-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_auto_20191006_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
