# Generated by Django 2.2.6 on 2019-10-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_answer_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersubmission',
            name='token',
            field=models.CharField(default='', max_length=255),
        ),
    ]
