# Generated by Django 2.2.6 on 2019-10-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_auto_20191011_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessment.Assessment')),
            ],
            options={
                'db_table': 'assessment_attempts',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='answer',
            name='assessment_take',
        ),
        migrations.AlterField(
            model_name='answersubmission',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AssessmentTake',
        ),
        migrations.AddField(
            model_name='answer',
            name='assessment_attempt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessment.AssessmentAttempt'),
            preserve_default=False,
        ),
    ]
