# Generated by Django 2.2.6 on 2019-10-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0008_auto_20191011_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
