# Generated by Django 2.2.6 on 2019-10-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_answer_passed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'managed': True, 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='answersubmission',
            options={'managed': True, 'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='answersubmission',
            name='response',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
