# Generated by Django 2.2.6 on 2019-10-22 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_auto_20191011_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(choices=[('java', 'Java'), ('javascript', 'Javascript'), ('python', 'Python'), ('ruby', 'Ruby')], max_length=255)),
                ('code', models.TextField()),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'code_submissions',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='answersubmission',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessment.Answer'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='language',
            field=models.CharField(choices=[('java', 'Java'), ('javascript', 'Javascript'), ('python', 'Python'), ('ruby', 'Ruby')], max_length=255),
        ),
    ]
