# Generated by Django 2.2.6 on 2019-10-22 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_auto_20191022_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeSubmission',
        ),
        migrations.AddField(
            model_name='answersubmission',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_submissions', to='assessment.Question'),
        ),
        migrations.AlterField(
            model_name='answersubmission',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessment.Answer'),
        ),
        migrations.AlterField(
            model_name='answersubmission',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
