# Generated by Django 2.2.6 on 2019-10-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_auto_20191022_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersubmission',
            name='identifier',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
