# Generated by Django 2.2.6 on 2019-10-24 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_answersubmission_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersubmission',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_submissions', to='assessment.Question'),
        ),
    ]
