# Generated by Django 2.2.6 on 2019-11-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0015_auto_20191025_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='wrap_solution',
            field=models.BooleanField(default=False),
        ),
    ]
