# Generated by Django 2.2.6 on 2020-01-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0017_remove_question_wrap_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='wrap_output',
            field=models.BooleanField(default=False),
        ),
    ]
